set(${PROJECT_NAME_PREFIX}3RD_PARTY_LIBRARY_PATH ${PROJECT_SOURCE_DIR}/3rd-party)

include(${${PROJECT_NAME_PREFIX}3RD_PARTY_LIBRARY_PATH}/freetype/freetype.cmake)
include(${${PROJECT_NAME_PREFIX}3RD_PARTY_LIBRARY_PATH}/stb/stb.cmake)
include(${${PROJECT_NAME_PREFIX}3RD_PARTY_LIBRARY_PATH}/glfw/glfw.cmake)
